In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Creating a Summary of all available data

In advance of extracting and preparing data, we want to first identify if the data is suitable for our purposes.  This had previously been done manually, but we are now automating and looping through the full dataset

In [2]:
# Household information import
# This table provides data for classification we will use

df_hhinfo = pd.read_csv('../raw_data/household_information.csv')
df_hhinfo = df_hhinfo[['LCLid', 'stdorToU','Acorn','Acorn_grouped','file','Groups','Correct_ACORN_group']]
df_hhinfo

,LCLid,stdorToU,Acorn,Acorn_grouped,file,Groups,Correct_ACORN_group
0,MAC000002,Std,ACORN-A,Affluent,block_0,Lavish Lifestyles,Affluent Achievers
1,MAC003613,Std,ACORN-A,Affluent,block_0,Lavish Lifestyles,Affluent Achievers
2,MAC003597,Std,ACORN-A,Affluent,block_0,Lavish Lifestyles,Affluent Achievers
3,MAC003579,Std,ACORN-A,Affluent,block_0,Lavish Lifestyles,Affluent Achievers
4,MAC003566,Std,ACORN-A,Affluent,block_0,Lavish Lifestyles,Affluent Achievers
...,...,...,...,...,...,...,...
5510,MAC002185,Std,ACORN-Q,Adversity,block_110,Difficult Circumstances,Urban Adversity
5511,MAC002347,Std,ACORN-Q,Adversity,block_110,Difficult Circumstances,Urban Adversity
5512,MAC000088,ToU,ACORN-Q,Adversity,block_110,Difficult Circumstances,Urban Adversity
5513,MAC002331,Std,ACORN-Q,Adversity,block_110,Difficult Circumstances,Urban Adversity
5514,MAC000318,Std,ACORN-Q,Adversity,block_110,Difficult Circumstances,Urban Adversity

In [3]:
# Block importing
# There are 111 blocks of data to be iterated through

# Create empty lists for iteration
housename = []
start_date = []
end_date = []
count = []
zeros = []
tariff = []
group = []
classification = []
acorn = []
block = []

for j in range(0, 112):
    # define filepath
    filepath = f'../raw_data/halfhourly_dataset/block_{j}.csv'
    
    # load individual blocks
    df_block = pd.read_csv(filepath)
    
    # Convert DateTime column to DateTime format for keymatching and ease of viewing
    df_block['DateTime'] = pd.to_datetime(df_block['tstp'])
    df_block.drop(columns = 'tstp', inplace = True)
    
    # Remove text strings with 'Null' value in them to allow us to convert energy usage to float
    df_block.drop(df_block[df_block['energy(kWh/hh)'] == 'Null'].index, inplace = True)
    df_block['energy(kWh/hh)'] = df_block['energy(kWh/hh)'].astype(float)
    
    # Store the LCLid's in a string called houselist for each block
    houselist = df_block['LCLid'].unique()
    
    # Status for iteration
    print(f'Now appending block {j} ...')
    
    # Append data from each block to lists to form a new summary dataframe
    for i in range (0,len(houselist)):
        housename.append(houselist[i])
        start_date.append(df_block[df_block['LCLid'] == houselist[i]]['DateTime'].iloc[0])
        end_date.append(df_block[df_block['LCLid'] == houselist[i]]['DateTime'].iloc[-1])
        count.append(df_block[df_block['LCLid'] == houselist[i]].count()[0])
        zeros.append((df_block[df_block['LCLid'] == houselist[i]]['energy(kWh/hh)'] == 0).sum())
        if houselist[i] in df_hhinfo['LCLid'].tolist():
            tariff.append((df_hhinfo[df_hhinfo['LCLid'] == houselist[i]]['stdorToU'].iloc[0]))
            acorn.append((df_hhinfo[df_hhinfo['LCLid'] == houselist[i]]['Acorn'].iloc[0]))
            block.append((df_hhinfo[df_hhinfo['LCLid'] == houselist[i]]['file'].iloc[0]))
            group.append((df_hhinfo[df_hhinfo['LCLid'] == houselist[i]]['Groups'].iloc[0]))
            classification.append((df_hhinfo[df_hhinfo['LCLid'] == houselist[i]]['Correct_ACORN_group'].iloc[0]))
        else:
            tariff.append('No Data')
            acorn.append('No Data')
            block.append('No Data')
            group.append('No Data')
            classification.append('No Data')

Now appending block 0 ...
Now appending block 1 ...
Now appending block 2 ...
Now appending block 3 ...
Now appending block 4 ...
Now appending block 5 ...
Now appending block 6 ...
Now appending block 7 ...
Now appending block 8 ...

/tmp/ipykernel_19856/2210807341.py:21: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_block = pd.read_csv(filepath)

Now appending block 9 ...
Now appending block 10 ...
Now appending block 11 ...

/tmp/ipykernel_19856/2210807341.py:21: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_block = pd.read_csv(filepath)

Now appending block 12 ...

/tmp/ipykernel_19856/2210807341.py:21: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_block = pd.read_csv(filepath)

Now appending block 13 ...
Now appending block 14 ...
Now appending block 15 ...
Now appending block 16 ...
Now appending block 17 ...
Now appending block 18 ...

/tmp/ipykernel_19856/2210807341.py:21: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_block = pd.read_csv(filepath)

Now appending block 19 ...
Now appending block 20 ...
Now appending block 21 ...
Now appending block 22 ...
Now appending block 23 ...
Now appending block 24 ...
Now appending block 25 ...
Now appending block 26 ...
Now appending block 27 ...
Now appending block 28 ...
Now appending block 29 ...
Now appending block 30 ...
Now appending block 31 ...
Now appending block 32 ...

/tmp/ipykernel_19856/2210807341.py:21: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_block = pd.read_csv(filepath)

Now appending block 33 ...
Now appending block 34 ...
Now appending block 35 ...
Now appending block 36 ...
Now appending block 37 ...
Now appending block 38 ...
Now appending block 39 ...
Now appending block 40 ...
Now appending block 41 ...
Now appending block 42 ...
Now appending block 43 ...
Now appending block 44 ...

/tmp/ipykernel_19856/2210807341.py:21: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_block = pd.read_csv(filepath)

Now appending block 45 ...
Now appending block 46 ...
Now appending block 47 ...
Now appending block 48 ...
Now appending block 49 ...
Now appending block 50 ...

/tmp/ipykernel_19856/2210807341.py:21: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_block = pd.read_csv(filepath)

Now appending block 51 ...
Now appending block 52 ...
Now appending block 53 ...
Now appending block 54 ...
Now appending block 55 ...
Now appending block 56 ...
Now appending block 57 ...
Now appending block 58 ...
Now appending block 59 ...
Now appending block 60 ...
Now appending block 61 ...
Now appending block 62 ...
Now appending block 63 ...
Now appending block 64 ...
Now appending block 65 ...
Now appending block 66 ...
Now appending block 67 ...
Now appending block 68 ...
Now appending block 69 ...
Now appending block 70 ...
Now appending block 71 ...
Now appending block 72 ...
Now appending block 73 ...
Now appending block 74 ...
Now appending block 75 ...
Now appending block 76 ...
Now appending block 77 ...
Now appending block 78 ...
Now appending block 79 ...
Now appending block 80 ...
Now appending block 81 ...
Now appending block 82 ...
Now appending block 83 ...
Now appending block 84 ...
Now appending block 85 ...
Now appending block 86 ...
Now appending block 87 ...
Now appending block 88 ...
Now appending block 89 ...
Now appending block 90 ...
Now appending block 91 ...
Now appending block 92 ...
Now appending block 93 ...
Now appending block 94 ...
Now appending block 95 ...
Now appending block 96 ...
Now appending block 97 ...
Now appending block 98 ...
Now appending block 99 ...
Now appending block 100 ...
Now appending block 101 ...
Now appending block 102 ...
Now appending block 103 ...
Now appending block 104 ...
Now appending block 105 ...
Now appending block 106 ...
Now appending block 107 ...

/tmp/ipykernel_19856/2210807341.py:21: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_block = pd.read_csv(filepath)

Now appending block 108 ...
Now appending block 109 ...
Now appending block 110 ...
Now appending block 111 ...

In [11]:
# Creating a DataFrame with the lists created through iteration

summary = pd.DataFrame({'LCLid': housename, 'start_date':start_date, 'end_date':end_date, 'data_points':count, 'zeros':zeros, 'tariff': tariff, 'Block':block, 'Acorn':acorn, 'Group':group, 'Classification':classification})

In [14]:
# Creating two new columns from existing DateTime data

summary['number_of_days'] = (summary['end_date'] - summary['start_date']).dt.days
summary['missing_hh'] = (((summary['end_date'] - summary['start_date']).dt.total_seconds() / 1800) + 1) - summary['data_points']
summary['missing_hh'] = summary['missing_hh'].astype(int)

In [16]:
# Reordering columns and viewing final table

summary = summary[['LCLid', 'start_date', 'end_date', 'number_of_days', 'data_points', 'missing_hh', 'zeros', 'tariff', 'Block', 'Acorn', 'Group', 'Classification']]
summary

,LCLid,start_date,end_date,number_of_days,data_points,missing_hh,zeros,tariff,Block,Acorn,Group,Classification
0,MAC000002,2012-10-12 00:30:00,2014-02-28 00:00:00,503,24140,52,21,Std,block_0,ACORN-A,Lavish Lifestyles,Affluent Achievers
1,MAC000246,2011-12-03 09:00:00,2014-02-28 00:00:00,817,39244,3,0,Std,block_0,ACORN-A,Lavish Lifestyles,Affluent Achievers
2,MAC000450,2012-03-22 15:30:00,2013-05-15 00:00:00,418,20027,55,0,Std,block_0,ACORN-A,Lavish Lifestyles,Affluent Achievers
3,MAC001074,2012-05-08 10:30:00,2012-12-20 23:30:00,226,10779,96,0,No Data,No Data,No Data,No Data,No Data
4,MAC003223,2012-09-17 12:30:00,2014-02-28 00:00:00,528,25366,2,0,Std,block_0,ACORN-A,Lavish Lifestyles,Affluent Achievers
...,...,...,...,...,...,...,...,...,...,...,...,...
5556,MAC003884,2012-10-25 16:00:00,2014-02-28 00:00:00,490,23537,0,22,No Data,No Data,No Data,No Data,No Data
5557,MAC004215,2012-05-23 10:00:00,2014-02-28 00:00:00,645,30986,3,1,No Data,No Data,No Data,No Data,No Data
5558,MAC004570,2011-12-23 10:00:00,2014-02-28 00:00:00,797,38281,4,0,No Data,No Data,No Data,No Data,No Data
5559,MAC004587,2012-07-11 08:00:00,2014-02-28 00:00:00,596,28631,10,0,No Data,No Data,No Data,No Data,No Data
5560,MAC004828,2012-04-05 13:30:00,2014-02-28 00:00:00,693,33160,126,11016,No Data,No Data,No Data,No Data,No Data

In [17]:
# Exporting dataset as CSV

filepath = '../raw_data/summary_v1.csv'
summary.to_csv(filepath)